# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.4.2 on Tue 30 Jan 2018 12:27:17 
# Model: Crop Pollination

import natcap.invest.pollination

args = {
    u'farm_vector_path': u'/data/pollination/farms.shp',
    u'guild_table_path': u'/data/pollination/guild_table.csv',
    u'landcover_biophysical_table_path': u'/data/pollination/landcover_biophysical_table.csv',
    u'landcover_raster_path': u'/data/pollination/landcover.tif',
    u'results_suffix': u'',
    u'workspace_dir': u'/workspace/pollination',
}

if __name__ == '__main__':
    natcap.invest.pollination.execute(args)
